# Generated by Django 4.2.6 on 2023-12-06 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('associated_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pal.group')),
            ],
        ),
    ]
